### ISSUE TITLE
You should add battlepass for chapter 2 i have some offers ids here 

### ISSUE THREAD

**Issue by MarvelcoDev** [Skiesuwu/Sirius#11]
s11
battleBundleOfferId: 93E992BC45D487A943D769845441ABA5
battlePassOfferId: 571D433C47E98F020EF099894CAF3B6A
tierOfferId: 70DBDA11425B10AF7A005D82DB54BC59

s12
battleBundleOfferId: 1355545DCD4C4627888C3EB5AE97D7BF
battlePassOfferId: 3D30A5B3128A4D539A548792BBFFACD4
tierOfferId: 689DD7694B70D4EF412B2D811A63C5BC

s13
battleBundleOfferId: A9DB423A2EDB4D8CA4D97204CE3F0D79
battlePassOfferId: A3A60070669140F198A0AFD38220CF22
tierOfferId: C677E22244C444256A79ACA0C59BAE7D

**Comment by MarvelcoDev** [comment]
others i dont have but s11 s12 s13 are most popular so others wont matter

**Comment by zinx28** [comment]
this is so basic to add just grab a higher chapter 2 version then you have all below

**Comment by zinx28** [comment]
+ provide the items for the battle pass

**Comment by MarvelcoDev** [comment]
> this is so basic to add just grab a higher chapter 2 version then you have all below

i said some my guy
