### ISSUE TITLE
hello, im having a problem

### ISSUE THREAD

**Issue by ojotaaa0124** [Skiesuwu/Sirius#5]
![image](https://github.com/Skiesuwu/Sirius/assets/154019101/72e67141-70a9-4581-a6f6-245ceeb4c9b1)

Thats the problem i have, when i open it, it stays like that, nothing works, can you help me? i made all the steps right

**Comment by Skiesuwu** [comment]
it doesnt mean anything, you can continue without any issues.

**Comment by ojotaaa0124** [comment]
ik that that doesnt mean anything, what i mean Is that the backend doesnt work, cuz it stays in connected to mongodb

**Comment by Skiesuwu** [comment]
try rebuilding?

**Comment by ojotaaa0124** [comment]
i tried, doesnt work, can you add me on discord and help me? obviously when you can
