### ISSUE TITLE
Backend is lacking endpoints

### ISSUE THREAD

**Issue by Salty-Coder** [Skiesuwu/Sirius#6]
Almost every request the client makes when launching, doesn't have an endpoint and just returns a 404.   
![image](https://github.com/Skiesuwu/Sirius/assets/59771980/5b53f3de-de3b-441c-b3df-3ef1879fde52)

**Comment by Skiesuwu** [comment]
those endpoints aren't that important but i will eventually add them

**Comment by Salty-Coder** [comment]
> those endpoints aren't that important but i will eventually add them

Not sure if its directly related or not then but the game fails to connect when I attempt to launch. Maybe the SSL proxying?

**Comment by Skiesuwu** [comment]
what build are you using

**Comment by Salty-Coder** [comment]
> what build are you using

Latest. Does it not work on latest?

**Comment by Skiesuwu** [comment]
I haven't tested latest
