### ISSUE TITLE
it doesnt let me in 

### ISSUE THREAD

**Issue by nicrepos** [Skiesuwu/Sirius#7]
![image](https://github.com/Skiesuwu/Sirius/assets/123606865/ed6e6772-ebbb-4784-927a-42a0d7ec823d)
it sends a bunch of requests and when i log in the lobby doesnt load, and when this happens it does that "handleclose" thing then the backend stops

**Comment by nicrepos** [comment]
![image](https://github.com/Skiesuwu/Sirius/assets/123606865/819fd066-1c2a-4da1-b7a3-9585e5981d28)
also sends this

**Comment by Skiesuwu** [comment]
what fortnite build are you using?
